name: Version_JTVAE
channels:
        # - conda-forge
        - pytorch
        - rdkit
dependencies:
        - python
        - pytorch
        - cudatoolkit
        - rdkit=2017.09
        - numpy
        - pandas
        - jupyter
        - matplotlib
        - seaborn
        - networkx
        - pip
